std = "luau"
exclude = ["*_packages/*", ".pesde/*", "dist*/*", "types/*", "fiu/*"]

[config]
global_usage = { ignore_pattern = "^RUNTIME$" } # Ignore the global value that will be injected by darklua
